### ISSUE TITLE
Invalid iBSS and iBEC patch files

### ISSUE THREAD

**Issue by nick-botticelli** [NyanSatan/Virtual-iBoot-Fun#1]
It appears that the patch files you included do not match the iBSS (iBSS.vma2.RELEASE.im4p) and iBEC (iBEC.vma2.RELEASE.im4p) included in 12.0.1 (21A559) IPSW. (e.g. iBSS patch is for 296696 byte file, but the iBSS included in UniversalMac 12.0.1 IPSW is 296735 bytes; this results in the patched file that cannot be read by img4). After attempting to create IMG4's of the iBSS/iBEC with patch + fixed size vs. without patch, it results in either nothing, or an iBoot crash.

Not sure if I am also doing something wrong. AVPBooter patch is fine (looks good in IDA Pro and can boot unpatched iBSS).

**Comment by NyanSatan** [comment]
Are you sure you're applying them against raw unpacked files and not against IM4P containers (as they originally are in IPSWs)?

**Comment by nick-botticelli** [comment]
It didn't hit me to extract them... Looks like patched iBSS and iBEC are booting now, thank you!
